# Generated by Django 4.2.16 on 2026-03-31 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cricket_teams',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('T10', 'T10')], default='T20', max_length=5)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], default='upcoming', max_length=15)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('series_name', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('squads_locked_at', models.DateTimeField(blank=True, null=True)),
                ('cricapi_match_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('result_summary', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.cricketteam')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.cricketteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='matches.cricketteam')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('BAT', 'Batsman'), ('BOW', 'Bowler'), ('AR', 'All-rounder'), ('WK', 'Wicketkeeper')], max_length=5)),
                ('batting_style', models.CharField(blank=True, max_length=50)),
                ('bowling_style', models.CharField(blank=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_active', models.BooleanField(default=True)),
                ('cricapi_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fantasy_credit', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('is_playing_xi', models.BooleanField(default=False)),
                ('is_announced', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='matches.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.cricketteam')),
            ],
            options={
                'db_table': 'squads',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
