# Generated by Django 4.2.16 on 2026-03-31 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('cashfree_transfer_id', models.CharField(blank=True, max_length=200)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('contest_entry', 'Contest Entry'), ('prize_credit', 'Prize Credit'), ('refund', 'Refund'), ('bonus', 'Bonus Credit'), ('tds', 'TDS Deduction')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('amount', models.BigIntegerField()),
                ('wallet_bucket', models.CharField(choices=[('deposit', 'Deposit Balance'), ('winnings', 'Winnings Balance'), ('bonus', 'Bonus Balance')], max_length=10)),
                ('cashfree_order_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('cashfree_payment_id', models.CharField(blank=True, max_length=200)),
                ('cashfree_signature', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contestentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
