# Generated by Django 4.2.16 on 2026-03-31 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('cricket', 'Cricket')], default='cricket', max_length=20)),
                ('format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('ALL', 'All Formats')], default='ALL', max_length=5)),
                ('event_name', models.CharField(max_length=100)),
                ('event_code', models.CharField(max_length=50, unique=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'points_rules',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('maiden_overs', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('run_outs_direct', models.IntegerField(default=0)),
                ('run_outs_indirect', models.IntegerField(default=0)),
                ('total_fantasy_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('points_breakdown', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='matches.player')),
            ],
            options={
                'db_table': 'player_match_scores',
                'unique_together': {('player', 'match')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(db_index=True)),
                ('total_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('prize_amount', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='contests.contest')),
                ('contest_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contestentry')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.userteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank'],
                'unique_together': {('contest', 'contest_entry')},
            },
        ),
    ]
