# Generated by Django 4.2.16 on 2026-03-31 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contest_type', models.CharField(choices=[('h2h', 'Head to Head'), ('small', 'Small League'), ('mega', 'Mega Contest'), ('free', 'Free Contest')], max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('entry_fee', models.BigIntegerField(default=0)),
                ('total_prize_pool', models.BigIntegerField(default=0)),
                ('max_entries', models.IntegerField(default=100)),
                ('min_entries', models.IntegerField(default=2)),
                ('current_entries', models.IntegerField(default=0)),
                ('prize_distribution', models.JSONField(default=list)),
                ('max_teams_per_user', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='matches.match')),
            ],
            options={
                'db_table': 'contests',
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Team 1', max_length=100)),
                ('total_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to='matches.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc_teams', to='matches.player')),
            ],
            options={
                'db_table': 'user_teams',
            },
        ),
        migrations.CreateModel(
            name='UserTeamPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('multiplier', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('final_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='contests.userteam')),
            ],
            options={
                'db_table': 'user_team_players',
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee_paid', models.BigIntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('prize_won', models.BigIntegerField(default=0)),
                ('tds_deducted', models.BigIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize_credited', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contests.contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='contests.userteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_entries',
                'unique_together': {('contest', 'team')},
            },
        ),
    ]
